- tag: "客户端开发项"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "客户端开发" ]

- tag: "待验收，且依赖发版[刘星辰]"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": ["待验收，且依赖发版--刘星辰" ]
- tag: "待验收，且依赖发版[周孝辉]"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": ["待验收，且依赖发版--周孝辉" ]
- tag: "待验收项[依赖版本]"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "待验收，且依赖发版"]

- tag: "待验收项[不依赖版本]"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "待验收，待配置上线"]

- tag: "待验收，待配置上线[刘星辰]"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "待验收，待配置上线--刘星辰"]
- tag: "待验收，待配置上线[周孝辉]"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "待验收，待配置上线--周孝辉"]

- tag: "日落项"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "日落" ]

- tag: "银联SDK"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "银联SDK" ]

- tag: "苏服办SDK"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "苏服办SDK" ]

- tag: "测试中(H5问题)"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "测试中，待H5修改（委办局修改）" ]

- tag: "测试中(BUG)"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "测试中，需要修复bug" ]

- tag: "测试中(无备注)"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "测试中" ]

- tag: "已沟通，配合测试中"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "已沟通，配合测试中（紫金数云修改）" ]

- tag: "已沟通，未响应"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "已沟通，未响应" ]

- tag: "未沟通，无联系方式"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "未沟通，无联系方式" ]

- tag: "未沟通，有联系方式"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "未沟通，有联系方式" ]

- tag: "未上线"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "未上线" ]

- tag: "已验收待上线[依赖版本]"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "已验收，待发版本"]

- tag: "已验收待上线[不依赖版本]"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": ["已验收，待配置上线" ]

- tag: "已上线"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "已上线" ]

- tag: "未开发项"
  conditions:
    "状态（已上线/正在开发/未开发/日落）": [ "未开发" ]